name: iOS Build

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest   # macOS runner required for iOS builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set iOS platform version
        run: |
          cd ios
          # Ensure platform is set to iOS 12.0
          sed -i '' "s/^# platform :ios, '9.0'/platform :ios, '12.0'/" Podfile || echo "platform :ios, '12.0'" >> Podfile
          pod install

      - name: Build iOS (unsigned)
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner-ipa
          path: build/ios/ipa/*.ipa
