name: iOS Build

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest   # 👈 macOS runner (required for iOS)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (unsigned)
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner-ipa
          path: build/ios/ipa/*.ipa
